### ISSUE TITLE
Decimals in the show-prices result field is incorrect.

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#126]
## Summary of Bug

decimals in the show-prices result field is incorrect.

## Version

https://github.com/ExocoreNetwork/exocore/pull/118/commits/67eaf49659f352c454bc0fc46362e1689de1fb42 + https://github.com/ExocoreNetwork/exocore/pull/100/commits/df8701ad4730114c948fe1884159cdb138218491

## Screenshots

`exocored q oracle show-prices 1 --node http://localhost:20000`
```
  - decimal: 18
    price: "291647813247"
    round_id: "260"
    timestamp: "2024-07-08 05:56:13"
  token_id: "1"
```

while in the transaction, the decimal is **8**.

```
exocored q oracle list-recent-msg --node http://localhost:20000
pagination:
  next_key: null
  total: "0"
recent_msg:
- block: "4701811"
  msgs:
  - feeder_id: "1"
    p_sources:
    - desc: ""
      prices:
      - decimal: 8
        det_id: "110680464442257328995"
        price: "291647813247"
        timestamp: "2024-07-08 05:58:26"
      source_id: "1"
    validator: exo1yqcmfnvw9qwm85dwxkcnxjd77dlptf460uj69h
  - feeder_id: "1"
    p_sources:
    - desc: ""
      prices:
      - decimal: 8
        det_id: "110680464442257328995"
        price: "291647813247"
        timestamp: "2024-07-08 05:58:26"
      source_id: "1"
    validator: exo1xsjgf6z5wyx2vrqpuj3pz2er305jeej5p7lp2f
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
