### ISSUE TITLE
RoundID and Price does not update If initial_height >= startBaseBlock*(Integer)+Interval + 1 in genesis file

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#128]
## Summary of Bug

Set startBaseBlock and initial_height in the genesis file, startBaseBlock =20, when initial_height<31, the price and round Id update successfully.
when initial_height >=31, price and roundId does not update after price feeding.

## Version

PR #83 +  PR #86 (7cd1cfd842b4b0f21768d6802f41ab1163b6cd55) + develop branch

## Steps to Reproduce

1. Initialize an single validator node with genesis file **start_base_block** set as **20**, interval as `10`, for example, and **initial_height** as >=**31**, and the price feeder miss price feeding for 31~33. 

```
        "token_feeders": [
          {
            "token_id": "0",
            "rule_id": "0",
            "start_round_id": "0",
            "start_base_block": "0",
            "interval": "0",
            "end_block": "0"
          },
          {
            "token_id": "1",
            "rule_id": "1",
            "start_round_id": "1",
            "start_base_block": "20",
            "interval": "10",
            "end_block": "0"
          }
        ],
```
2. query oracle show-prices function, after the price feeder sumbit create-price message on block 41. the round ID and price is not updated.
`exocored q oracle show-prices 1`
```
prices:
  next_round_id: "2"
  price_list:
  - decimal: 0
    price: ""
    round_id: "0"
    timestamp: ""
  - decimal: 0
    price: ""
    round_id: "1"
    timestamp: ""
  token_id: "1"
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
