### ISSUE TITLE
Operator USD Value not update after a new token/asset is feeding price by oracle

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#165]
Exocore version:  PR #157 + develop branch (03696824ba5dcb6b0f8875ab061bffa30b64e521)

Reproduction Steps:
1. start local_node.sh script, add --oracle --grpc.enable flag, default minimum self delegation is 100USD.
2. Add a second token(`wstETH`) in oracle module on the same client chain with the default asset.
3. Update oracle params and token feeder field, start to feed price to the second token.
4. Register the second token(`wstETH`) to assets module.
5. Start a 2nd node and register it as validator.
6. Deposit 1e18 wstETH and delegate to the new registered validator.
7. Check the staking amount of the staker and validator delegation amount, they are both correct.
8. Check the price of token wstETH and current price is `311666480041` with decimal 8.
9. Check the validator set, it is found that there is still only 1 validator.
Expect Result: there should be two validators in the validator set, since the 2nd validator has self delegation greater than 100.
11. Check operator USD value of the  new registered validator, it is all 0.
Expect Result: the operator USD value should be the amount * price /decimal
12. Try to deposit and delegate the 1st token to the new validator, check operator USD value, the USD value is not 0 anymore, but the 1st token amount * price/decimal. 

exo12csf6aseun45uhnmrahf9ng05w8qf4a08vy6r9 is the new registered operator

```
exocored q operator get-all-operators   
operator_acc_addrs:
- exo18cggcpvwspnd5c6ny8wrqxpffj5zmhklprtnph
- exo12csf6aseun45uhnmrahf9ng05w8qf4a08vy6r9
pagination:
  next_key: null
  total: "2"
```

```
exocored q assets QueOperatorAssetInfos  exo12csf6aseun45uhnmrahf9ng05w8qf4a08vy6r9
asset_infos:
  0xb82381a3fbd3fafa77b3a7be693342618240067b_0x65:
    operator_share: "1000000000000000000.000000000000000000"
    total_amount: "1000000000000000000"
    total_share: "1000000000000000000.000000000000000000"
    wait_unbonding_amount: "0"
```

oracle params
```
exocored q oracle params  
params:
  chains:
  - desc: '-'
    name: '-'
  - desc: '-'
    name: Ethereum
  max_det_id: 5
  max_nonce: 3
  max_size_prices: 100
  mode: 1
  rules:
  - nom: null
    source_ids: []
  - nom: null
    source_ids:
    - "0"
  sources:
  - deterministic: false
    entry: null
    name: 0 position is reserved
    valid: false
  - deterministic: true
    entry:
      offchain:
        "0": ""
      onchain: {}
    name: Chainlink
    valid: true
  threshold_a: 2
  threshold_b: 3
  token_feeders:
  - end_block: "0"
    interval: "0"
    rule_id: "0"
    start_base_block: "0"
    start_round_id: "0"
    token_id: "0"
  - end_block: "0"
    interval: "10"
    rule_id: "1"
    start_base_block: "260"
    start_round_id: "1"
    token_id: "1"
  - end_block: "0"
    interval: "30"
    rule_id: "0"
    start_base_block: "900"
    start_round_id: "1"
    token_id: "2"
  tokens:
  - active: false
    asset_id: ""
    chain_id: "0"
    contract_address: ""
    decimal: 0
    name: ""
  - active: true
    asset_id: 0xdac17f958d2ee523a2206206994597c13d831ec7_0x65
    chain_id: "1"
    contract_address: 0x
    decimal: 8
    name: ETH
  - active: true
    asset_id: 0xb82381a3fbd3fafa77b3a7be693342618240067b_0x65
    chain_id: "1"
    contract_address: ""
    decimal: 8
    name: wstETH
```

```
exocored q avs AVSAddrByChainID exocoretestnet_233-2  
avs_address: 0xAa089Ba103f765fCeA44808BD3d4073523254C57
```

```
exocored q operator get-operator-cons-key exo12csf6aseun45uhnmrahf9ng05w8qf4a08vy6r9 exocoretestnet_233-2

public_key:
  ed25519: q96U4ytp6LuTMaxyS8/ok9zGOAgvnZ3qJCiDwCxPReo=
```

```
exocored tendermint show-validator --home /root/jessyTest157/
{"@type":"/cosmos.crypto.ed25519.PubKey","key":"q96U4ytp6LuTMaxyS8/ok9zGOAgvnZ3qJCiDwCxPReo="}
```

```
exocored q operator QueryOperatorUSDValue exo18cggcpvwspnd5c6ny8wrqxpffj5zmhklprtrtnph 0xAa089Ba103f765fCeA44808BD3d4073523254C57
usd_values:
  active_usd_value: "13243850.000000000000000000"
  self_usd_value: "13243850.000000000000000000"
  total_usd_value: "13243850.000000000000000000"
```

```
exocored q operator QueryOperatorUSDValue exo12csf6aseun45uhnmrahf9ng05w8qf4a08vy6r9 0xAa089Ba103f765fCeA44808BD3d4073523254C57
usd_values:
  active_usd_value: "0.000000000000000000"
  self_usd_value: "0.000000000000000000"
  total_usd_value: "0.000000000000000000"
```
