### ISSUE TITLE
Operator USD is 0 at the end of first Epoch When Starting 

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#177]
## Summary of Bug

get OperatorUSD returns 0 When network started before the end of first epoch

## Version

https://github.com/ExocoreNetwork/exocore/commit/5a59729acfc97e661668ad80cd62990ff565b616

## Steps to Reproduce

1. change the epoch to day in local_node.sh
2. run local_node.sh
3. exocored q operator QueryOperatorUSDValue exo18cggcpvwspnd5c6ny8wrqxpffj5zmhklprtnph  0xAa089Ba103f765fCeA44808BD3d4073523254C57

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by TimmyExogenous** [comment]
This issue will be fixed after merging the #PR108

**Comment by cloud8little** [comment]
Verified on four validators localnet with epoch is day
```
exocored q operator QueryOperatorUSDValue exo1c5x7mxphvgavjhu0au9jjqnfqcyspevtyy27mz 0xaa089ba103f765fcea44808bd3d4073523254c57 --node http://localhost:20000
usd_values:
  active_usd_value: "8525580.895040000000000000"
  self_usd_value: "7750528.086400000000000000"
  total_usd_value: "8525580.895040000000000000"
```
