### ISSUE TITLE
[Oracle Miss Price Feeding] Validator who does not Feeding Price Should Get Jailed When miss window Greater than report_window*minimun_report_per_window

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#289]
## Summary of Bug

As design, if a validator does not feed price, when miss window Greater than report_window*minimun_report_per_window, this validator should be jailed.

## Version

exocore:  https://github.com/leonz789/exocore/releases/tag/v1.0.13
price-feeder:  https://github.com/ExocoreNetwork/price-feeder/commit/3889000206b8e300ce30364da92c2adec24b18c0 

## Steps to Reproduce

1. Start four validators network using https://github.com/cloud8little/ExocoreValidators,disable --oracle option. exocore binary: https://github.com/leonz789/exocore/releases/tag/v1.0.13
2. Replace all genesis file with [genesis_v7_oracleMissPriceFeeding.json](https://github.com/user-attachments/files/18437437/genesis_v7_oracleMissPriceFeeding.json)
3. Start price feeder debug mode for four nodes separately.
price feeder binary: https://github.com/ExocoreNetwork/price-feeder/commit/3889000206b8e300ce30364da92c2adec24b18c0 
4. Run manual price feeder script, this script will manually feed price for validator1~3, with token ID=1 & 2, at the height 15/45/75. which means the validator 4 should miss (token counts)2 * round(3) = 6, which is greater than report_window*minimun_report_per_window = 5.

[manualPricefeed_issue.txt](https://github.com/user-attachments/files/18437492/manualPricefeed_issue.txt)

5. **Expected Result:**
validator 4 should get jailed after height 81.
**Actual Result:** 
validator 4 is not jailed.

## Screenshots

check log contained "missed"
```
729:9:30AM INF oracle_absent validator height=51 missed=1 module=x/oracle threshold=5 validator=exovalcons1gzcn6md2xwregl9qjkxjtrfpg0f57g5y3xqmxt
730:9:30AM INF oracle_absent validator height=51 missed=2 module=x/oracle threshold=5 validator=exovalcons1gzcn6md2xwregl9qjkxjtrfpg0f57g5y3xqmxt
1121:9:32AM INF oracle_absent validator height=81 missed=3 module=x/oracle threshold=5 validator=exovalcons1gzcn6md2xwregl9qjkxjtrfpg0f57g5y3xqmxt
1122:9:32AM INF oracle_absent validator height=81 missed=4 module=x/oracle threshold=5 validator=exovalcons1gzcn6md2xwregl9qjkxjtrfpg0f57g5y3xqmxt
```

token ID = 1 prices: 

```
  price_list:
  - decimal: 8
    price: "97908000000"
    round_id: "1"
    timestamp: "2025-01-16 09:28:22"
  - decimal: 8
    price: "97918000000"
    round_id: "2"
    timestamp: "2025-01-16 09:30:03"
  - decimal: 8
    price: "97928000000"
    round_id: "3"
    timestamp: "2025-01-16 09:31:41"
```

token ID = 2 prices.
```
exocored q oracle show-prices 2 --node http://localhost:20000
prices:
  next_round_id: "4"
  price_list:
  - decimal: 8
    price: "17908000000"
    round_id: "1"
    timestamp: "2025-01-16 09:28:22"
  - decimal: 8
    price: "15908000000"
    round_id: "2"
    timestamp: "2025-01-16 09:30:03"
  - decimal: 8
    price: "16908000000"
    round_id: "3"
    timestamp: "2025-01-16 09:31:45"
  token_id: "2"
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
