### ISSUE TITLE
When duplicate asset name registered, no error returned, and the original asset address is corrupted

### ISSUE THREAD

**Issue by cloud8little** [ExocoreNetwork/exocore#340]
## Summary of Bug

When an asset is registered with name, for example "SOL", then register a new asset with the same name but with different asset address, the original asset address is corrupted.

## Steps to Reproduce

For simplicity, I will use the [assetsTool ](https://github.com/cloud8little/AssetsTool/releases/tag/v0.0.6) to register client chain and token.

1. run local_node.sh 
2. Register client chain Solana. 
3. `assetcli register-or-update-client-chain --rpcUrl http://localhost:8545 --privateKey D196DCA836F8AC2FFF45B3C9F0113825CCBB33FA1B39737B948503B263ED75AE --clientChainID 40168 --addressLength 32 --name Solana --metaInfo "Solana Official" --signatureType "ed25519"`
4. Register new token SOL. 
5. `assetcli register-token --rpcUrl http://localhost:8545 --privateKey C26A874A75B028638D477DDF31EB8627899CB505798DF70D2DD2A631F9CAE7A4 --assetAddress 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee --decimals 9 --name SOL --metaData "SOL for Solana" --oracleInfo "SOL,solana,8" --layerZeroID 40168`
6. register a new client chain XRP.
7. assetcli register-or-update-client-chain --rpcUrl http://localhost:8545 --privateKey C26A874A75B028638D477DDF31EB8627899CB505798DF70D2DD2A631F9CAE7A4 --clientChainID 2 --addressLength 20 --name XRPL --metaInfo "XRP LEDGER" --signatureType "ECDSA"
8. register a new token XRP, but mistakely input the same name SOL.
9. assetcli register-token --rpcUrl http://localhost:8545 --privateKey C26A874A75B028638D477DDF31EB8627899CB505798DF70D2DD2A631F9CAE7A4 --assetAddress 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb --decimals 6 --name SOL --metaData "SOL for Solana" --oracleInfo "XRP,xrp,6" --layerZeroID 2
10. check all staking assets.
11. imuad q assets all-staking-assets
12.
```
 - asset_basic_info:
    address: 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
    decimals: 6
    imua_chain_index: "0"
    layer_zero_chain_id: "2"
    meta_info: SOL for Solana
    name: SOL
    symbol: ""
  staking_total_amount: "0"
- asset_basic_info:
    address: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000
    decimals: 9
    imua_chain_index: "0"
    layer_zero_chain_id: "40168"
    meta_info: SOL for Solana
    name: SOL
    symbol: ""
  staking_total_amount: "0"
```

the oracle params goes like this:

```
  - active: true
    asset_id: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000_0x9ce8
    chain_id: "2"
    contract_address: ""
    decimal: 8
    name: SOL
  - active: true
    asset_id: 0xbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb_0x2
    chain_id: "3"
    contract_address: ""
    decimal: 6
    name: XRP
```

## Additional context

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
